### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by andrevvalle** [front-end-carioca/fec-2015#1]
Hey, precisamos de ajuda pra fazer o responsivo. Estamos usando a grid do foundation, sinta-se a vontade para contribuir.

OBS. Para contribuir
1. Crie uma branch com seu nome para contribuição.
2. Apesar do projeto estar sendo feito na correria tentar respeitar a semântica e organização é sempre muito bem vindo :laughing:

**Comment by educostachaves** [comment]
Boa Noite pessoal. Conversei essa semana com o @pedropolisenso, e fiquei de ajudar você com relação ao site. To respondendo só agora por que eu estava vendo o código, e essa semana está muito pegada no escritório. Vou tentar ajudar vocês como possível galera. Blz?! Abraços!

**Comment by pedropolisenso** [comment]
Perfeito @educostachaves obrigado!
