### ISSUE TITLE
Botões - melhor visualização

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2015#12]
Os botões de "seja patrocinador" e "inscreva-se" o hover pode ser laranja, pois o hover branco fica estranho um tipo de branco no branco, saca? Temos poucas cores então vamos colorir de acordo com o tema do site

**Comment by afonsopacifer** [comment]
Fiz essa alteração aqui... se quiserem mesmo,eu mando o PR.
![screen shot 2015-05-04 at 9 02 23 pm](https://cloud.githubusercontent.com/assets/6748866/7465100/f3e1bf00-f2a0-11e4-9f33-a46fa4023f2b.png)

**Comment by afonsopacifer** [comment]
OBS: Para ficar mais claro acho que poderiam colocar umas labels,
so para identificar se e uma melhoria a fazer ou
se é uma proposta de melhoria para ser discutida ainda, sei la :P

**Comment by andrevvalle** [comment]
@afonsopacifer manda um PR sim :)

**Comment by afonsopacifer** [comment]
Blz, ta lá :D

**Comment by andrevvalle** [comment]
Thanks! :laughing:
