### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2015#2]
@andrevvalle precisamos atualizar a REDME.md e colocar as tecnologias que, realmente, estão sendo usadas, sacou? Para não atrapalhar na contribuição da galera.

PS: Assim que atualizar, feche essa issue!

**Comment by andrevvalle** [comment]
@pedropolisenso mano o README está atualizado.

**Comment by pedropolisenso** [comment]
@andrevvalle você ta usando jasmine?

**Comment by andrevvalle** [comment]
@pedropolisenso sim cara, é só vc olhar no projeto.
o README está atualizado ;)
