### ISSUE TITLE
Dar foco na sessão selecionada

### ISSUE THREAD

**Issue by brunopulis** [front-end-carioca/fec-2015#25]
Ao selecionar por exemplo o menu **Sobre**  via teclado ele vai a sessão escolhida, porém ao dar um novo tab ele sai da sessão, isto ocorre porque o Chrome perdeu a referência de onde ele tem que ir. 

Seria interessante colocar um **tabindex="-1"** em todas as sessões para dar o foco pretendido nas sessões.

**Comment by andrevvalle** [comment]
Legal, está aberto para quem puder implementar.
@brunopulis valeu :laughing:

**Comment by brunopulis** [comment]
@andrevvalle  eu até tentei mas não consegui colocar nas section, eu conheço pouco de Jade.

**Comment by andrevvalle** [comment]
@brunopulis tranquilo, se ninguém fizer, eu faço assim que tiver um tempo.

**Comment by brunopulis** [comment]
@andrevvalle :smile: vou tentar resolver isso assim que chegar em casa

**Comment by andrevvalle** [comment]
Close por falta de tempo.
