### ISSUE TITLE
Ao carregar o site, não mostra a barra de navegação

### ISSUE THREAD

**Issue by albertosouza** [front-end-carioca/fec-2015#26]
Resolução: 1366 x 768

Problemas:
- A barra de navegação do browser não aparece
- Não é possível dar scroll para baixo ( só é possível descer clicando nos links ) 

Como aparece:
![exemplo](http://wejs.org/public/static/2015-print-brasil-carioca.jpg)

**Comment by andrevvalle** [comment]
@albertosouza Obrigado por reportar o bug, vou verificar agora ;)

**Comment by albertosouza** [comment]
Ok, 

eu testei em outra tela maior e o bug apareceu na segunda vez que carreguei a página e não aparece erro no console do navegador.

OBS.: estou usando o navegador Chrome atualizado.
