### ISSUE TITLE
Parallax Banner

### ISSUE THREAD

**Issue by andrevvalle** [front-end-carioca/fec-2015#3]
Corrigir e deixar funcionando em todos os browsers.
com exceção do IE :)

BUG: O banner "AQUEÇAM OS MOTORES :)" está com "background-attachment: fixed", porem só funciona no firefox. No chrome e outros fica com um Bug nesse parallax.

**Comment by pedropolisenso** [comment]
@andrevvalle você ficou de dar uma olhada nisso, conseguiu ver já?

**Comment by andrevvalle** [comment]
Done!
