### ISSUE TITLE
Bug do Footer

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2015#7]
Existe um bug no footer que ele repete abaixo do footer a imagem da header, precisamos corrigir isso!

**Comment by andrevvalle** [comment]
@pedropolisenso por favor, reproduza este bug e me envie um print pois não encontrei este bug.

**Comment by pedropolisenso** [comment]
@andrevvalle esse problemas podemos resolver na hora do responsivo, só precisamos agilizar as coisas, porque tem pessoas já reclamando e tal.
