### ISSUE TITLE
Bug de resolução

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2015#9]
Em monitores menores os botões de **seja patrocinador** e **inscreva-se** não aparecem, precisamos trabalhar com as MEDIAS QUERIES

**Comment by afonsopacifer** [comment]
Aqui no meu macbook 11'' ta assim, já dei fork, hoje quando chegar do trampo vou tentar arrumar :D

**Comment by afonsopacifer** [comment]
Se bem que testei agora, e ta OK, a bug já foi resolvido?

**Comment by andrevvalle** [comment]
@afonsopacifer acredito que ainda não foi corrigido, só testando as resoluções para ter certeza.
Fique a vontade para contribuir ;)

**Comment by afonsopacifer** [comment]
Show, a noite eu testo, se precisar eu mexo, posto aqui o bug e mando  PR

**Comment by afonsopacifer** [comment]
testei no responsinator e em alguns devices aqui, e pelo o que eu vi, 
Os paranaues da responsividade estão precisando de ajustes mesmo, como foi dito na outra issue, acho q isso que esta causando o bug relatado aqui,
 de qualquer forma vou tentar ajeitar..
